require("options")

-- require("plugins.telescope")
-- require("plugins.bufferline")
require("plugins.toggleterm")
require("plugins.nvimtree")
require("plugins.treesitter")
-- require("plugins.galaxyline")
require("plugins.lualine")
require("plugins.lsp")
require('plugins.compe')
require("plugins.others")
-- require("plugins.trouble")
-- require("plugins.dap")

require("mappings")
